plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.sonarqube' version '4.4.1.3373'
}
tasks.named('bootJar') {
	archiveFileName = 'repo_task-0.0.1-SNAPSHOT.jar'
}


group = 'com.task.api'
version = '0.0.1-SNAPSHOT'
description = 'Description: Task microservice 001 - CRUD básico con WebFlux y Postgres'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot & WebFlux
	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// PostgreSQL R2DBC Driver
	implementation 'org.postgresql:r2dbc-postgresql:1.0.5.RELEASE'
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'org.postgresql:r2dbc-postgresql'

	// Spring Boot Actuator (opcional para métricas y health)
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	// MapStruct
	implementation 'org.mapstruct:mapstruct:1.6.0'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.0'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// H2 Reactive
	implementation 'io.r2dbc:r2dbc-h2'
	runtimeOnly 'com.h2database:h2'

	// Tests
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test) {
	useJUnitPlatform()
}
