server:
  port: 8080

spring:
  application:
    name: task-api-001
  webflux:
    base-path: /task-api-001/api

  # Activa el perfil desde variable de entorno (por defecto: dev)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Importa el archivo configuration.yaml
  config:
    import: optional:classpath:configuration.yaml