postgres:
  host: ${POSTGRES_HOST:taskserver.postgres.database.azure.com}
  port: ${POSTGRES_PORT:5432}
  database: ${POSTGRES_DB:task}
  username: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:Manolo9315308+1}
  schema: ${POSTGRES_SCHEMA:public}

external:
  api:
    base-url: ${EXTERNAL_API_URL:http://localhost:8080}
    token: ${EXTERNAL_API_TOKEN:default-dev-token}

frontend:
  url: ${FRONT_URL:http://localhost:3000}